SECTION "Pics 1", ROMX

BulbasaurPicFront::   INCBIN "gfx/pokemon/front/bulbasaur.pic"
BulbasaurPicBack::    INCBIN "gfx/pokemon/back/bulbasaurb.pic"
IvysaurPicFront::     INCBIN "gfx/pokemon/front/ivysaur.pic"
IvysaurPicBack::      INCBIN "gfx/pokemon/back/ivysaurb.pic"
VenusaurPicFront::    INCBIN "gfx/pokemon/front/venusaur.pic"
VenusaurPicBack::     INCBIN "gfx/pokemon/back/venusaurb.pic"
CharmanderPicFront::  INCBIN "gfx/pokemon/front/charmander.pic"
CharmanderPicBack::   INCBIN "gfx/pokemon/back/charmanderb.pic"
CharmeleonPicFront::  INCBIN "gfx/pokemon/front/charmeleon.pic"
CharmeleonPicBack::   INCBIN "gfx/pokemon/back/charmeleonb.pic"
CharizardPicFront::   INCBIN "gfx/pokemon/front/charizard.pic"
CharizardPicBack::    INCBIN "gfx/pokemon/back/charizardb.pic"
SquirtlePicFront::    INCBIN "gfx/pokemon/front/squirtle.pic"
SquirtlePicBack::     INCBIN "gfx/pokemon/back/squirtleb.pic"
WartortlePicFront::   INCBIN "gfx/pokemon/front/wartortle.pic"
WartortlePicBack::    INCBIN "gfx/pokemon/back/wartortleb.pic"
BlastoisePicFront::   INCBIN "gfx/pokemon/front/blastoise.pic"
BlastoisePicBack::    INCBIN "gfx/pokemon/back/blastoiseb.pic"
CaterpiePicFront::    INCBIN "gfx/pokemon/front/caterpie.pic"
CaterpiePicBack::     INCBIN "gfx/pokemon/back/caterpieb.pic"
MetapodPicFront::     INCBIN "gfx/pokemon/front/metapod.pic"
MetapodPicBack::      INCBIN "gfx/pokemon/back/metapodb.pic"
ButterfreePicFront::  INCBIN "gfx/pokemon/front/butterfree.pic"
ButterfreePicBack::   INCBIN "gfx/pokemon/back/butterfreeb.pic"
WeedlePicFront::      INCBIN "gfx/pokemon/front/weedle.pic"
WeedlePicBack::       INCBIN "gfx/pokemon/back/weedleb.pic"
KakunaPicFront::      INCBIN "gfx/pokemon/front/kakuna.pic"
KakunaPicBack::       INCBIN "gfx/pokemon/back/kakunab.pic"
BeedrillPicFront::    INCBIN "gfx/pokemon/front/beedrill.pic"
BeedrillPicBack::     INCBIN "gfx/pokemon/back/beedrillb.pic"
PidgeyPicFront::      INCBIN "gfx/pokemon/front/pidgey.pic"
PidgeyPicBack::       INCBIN "gfx/pokemon/back/pidgeyb.pic"
PidgeottoPicFront::   INCBIN "gfx/pokemon/front/pidgeotto.pic"
PidgeottoPicBack::    INCBIN "gfx/pokemon/back/pidgeottob.pic"
PidgeotPicFront::     INCBIN "gfx/pokemon/front/pidgeot.pic"
PidgeotPicBack::      INCBIN "gfx/pokemon/back/pidgeotb.pic"
RattataPicFront::     INCBIN "gfx/pokemon/front/rattata.pic"
RattataPicBack::      INCBIN "gfx/pokemon/back/rattatab.pic"
RaticatePicFront::    INCBIN "gfx/pokemon/front/raticate.pic"
RaticatePicBack::     INCBIN "gfx/pokemon/back/raticateb.pic"
SpearowPicFront::     INCBIN "gfx/pokemon/front/spearow.pic"
SpearowPicBack::      INCBIN "gfx/pokemon/back/spearowb.pic"
FearowPicFront::      INCBIN "gfx/pokemon/front/fearow.pic"
FearowPicBack::       INCBIN "gfx/pokemon/back/fearowb.pic"
EkansPicFront::       INCBIN "gfx/pokemon/front/ekans.pic"
EkansPicBack::        INCBIN "gfx/pokemon/back/ekansb.pic"
ArbokPicFront::       INCBIN "gfx/pokemon/front/arbok.pic"
ArbokPicBack::        INCBIN "gfx/pokemon/back/arbokb.pic"
PikachuPicFront::     INCBIN "gfx/pokemon/front/pikachu.pic"
PikachuPicBack::      INCBIN "gfx/pokemon/back/pikachub.pic"
RaichuPicFront::      INCBIN "gfx/pokemon/front/raichu.pic"
RaichuPicBack::       INCBIN "gfx/pokemon/back/raichub.pic"

	ds $a3


SECTION "Pics 2", ROMX

SandshrewPicFront::   INCBIN "gfx/pokemon/front/sandshrew.pic"
SandshrewPicBack::    INCBIN "gfx/pokemon/back/sandshrewb.pic"
SandslashPicFront::   INCBIN "gfx/pokemon/front/sandslash.pic"
SandslashPicBack::    INCBIN "gfx/pokemon/back/sandslashb.pic"
NidoranFPicFront::    INCBIN "gfx/pokemon/front/nidoranf.pic"
NidoranFPicBack::     INCBIN "gfx/pokemon/back/nidoranfb.pic"
NidorinaPicFront::    INCBIN "gfx/pokemon/front/nidorina.pic"
NidorinaPicBack::     INCBIN "gfx/pokemon/back/nidorinab.pic"
NidoqueenPicFront::   INCBIN "gfx/pokemon/front/nidoqueen.pic"
NidoqueenPicBack::    INCBIN "gfx/pokemon/back/nidoqueenb.pic"
NidoranMPicFront::    INCBIN "gfx/pokemon/front/nidoranm.pic"
NidoranMPicBack::     INCBIN "gfx/pokemon/back/nidoranmb.pic"
NidorinoPicFront::    INCBIN "gfx/pokemon/front/nidorino.pic"
NidorinoPicBack::     INCBIN "gfx/pokemon/back/nidorinob.pic"
NidokingPicFront::    INCBIN "gfx/pokemon/front/nidoking.pic"
NidokingPicBack::     INCBIN "gfx/pokemon/back/nidokingb.pic"
ClefairyPicFront::    INCBIN "gfx/pokemon/front/clefairy.pic"
ClefairyPicBack::     INCBIN "gfx/pokemon/back/clefairyb.pic"
ClefablePicFront::    INCBIN "gfx/pokemon/front/clefable.pic"
ClefablePicBack::     INCBIN "gfx/pokemon/back/clefableb.pic"
VulpixPicFront::      INCBIN "gfx/pokemon/front/vulpix.pic"
VulpixPicBack::       INCBIN "gfx/pokemon/back/vulpixb.pic"
NinetalesPicFront::   INCBIN "gfx/pokemon/front/ninetales.pic"
NinetalesPicBack::    INCBIN "gfx/pokemon/back/ninetalesb.pic"
JigglypuffPicFront::  INCBIN "gfx/pokemon/front/jigglypuff.pic"
JigglypuffPicBack::   INCBIN "gfx/pokemon/back/jigglypuffb.pic"
WigglytuffPicFront::  INCBIN "gfx/pokemon/front/wigglytuff.pic"
WigglytuffPicBack::   INCBIN "gfx/pokemon/back/wigglytuffb.pic"
ZubatPicFront::       INCBIN "gfx/pokemon/front/zubat.pic"
ZubatPicBack::        INCBIN "gfx/pokemon/back/zubatb.pic"
GolbatPicFront::      INCBIN "gfx/pokemon/front/golbat.pic"
GolbatPicBack::       INCBIN "gfx/pokemon/back/golbatb.pic"
OddishPicFront::      INCBIN "gfx/pokemon/front/oddish.pic"
OddishPicBack::       INCBIN "gfx/pokemon/back/oddishb.pic"
GloomPicFront::       INCBIN "gfx/pokemon/front/gloom.pic"
GloomPicBack::        INCBIN "gfx/pokemon/back/gloomb.pic"
VileplumePicFront::   INCBIN "gfx/pokemon/front/vileplume.pic"
VileplumePicBack::    INCBIN "gfx/pokemon/back/vileplumeb.pic"
ParasPicFront::       INCBIN "gfx/pokemon/front/paras.pic"
ParasPicBack::        INCBIN "gfx/pokemon/back/parasb.pic"
ParasectPicFront::    INCBIN "gfx/pokemon/front/parasect.pic"
ParasectPicBack::     INCBIN "gfx/pokemon/back/parasectb.pic"
VenonatPicFront::     INCBIN "gfx/pokemon/front/venonat.pic"
VenonatPicBack::      INCBIN "gfx/pokemon/back/venonatb.pic"
VenomothPicFront::    INCBIN "gfx/pokemon/front/venomoth.pic"
VenomothPicBack::     INCBIN "gfx/pokemon/back/venomothb.pic"
DiglettPicFront::     INCBIN "gfx/pokemon/front/diglett.pic"
DiglettPicBack::      INCBIN "gfx/pokemon/back/diglettb.pic"
DugtrioPicFront::     INCBIN "gfx/pokemon/front/dugtrio.pic"
DugtrioPicBack::      INCBIN "gfx/pokemon/back/dugtriob.pic"

	ds $233


SECTION "Pics 3", ROMX

MeowthPicFront::      INCBIN "gfx/pokemon/front/meowth.pic"
MeowthPicBack::       INCBIN "gfx/pokemon/back/meowthb.pic"
PersianPicFront::     INCBIN "gfx/pokemon/front/persian.pic"
PersianPicBack::      INCBIN "gfx/pokemon/back/persianb.pic"
PsyduckPicFront::     INCBIN "gfx/pokemon/front/psyduck.pic"
PsyduckPicBack::      INCBIN "gfx/pokemon/back/psyduckb.pic"
GolduckPicFront::     INCBIN "gfx/pokemon/front/golduck.pic"
GolduckPicBack::      INCBIN "gfx/pokemon/back/golduckb.pic"
MankeyPicFront::      INCBIN "gfx/pokemon/front/mankey.pic"
MankeyPicBack::       INCBIN "gfx/pokemon/back/mankeyb.pic"
PrimeapePicFront::    INCBIN "gfx/pokemon/front/primeape.pic"
PrimeapePicBack::     INCBIN "gfx/pokemon/back/primeapeb.pic"
GrowlithePicFront::   INCBIN "gfx/pokemon/front/growlithe.pic"
GrowlithePicBack::    INCBIN "gfx/pokemon/back/growlitheb.pic"
ArcaninePicFront::    INCBIN "gfx/pokemon/front/arcanine.pic"
ArcaninePicBack::     INCBIN "gfx/pokemon/back/arcanineb.pic"
PoliwagPicFront::     INCBIN "gfx/pokemon/front/poliwag.pic"
PoliwagPicBack::      INCBIN "gfx/pokemon/back/poliwagb.pic"
PoliwhirlPicFront::   INCBIN "gfx/pokemon/front/poliwhirl.pic"
PoliwhirlPicBack::    INCBIN "gfx/pokemon/back/poliwhirlb.pic"
PoliwrathPicFront::   INCBIN "gfx/pokemon/front/poliwrath.pic"
PoliwrathPicBack::    INCBIN "gfx/pokemon/back/poliwrathb.pic"
AbraPicFront::        INCBIN "gfx/pokemon/front/abra.pic"
AbraPicBack::         INCBIN "gfx/pokemon/back/abrab.pic"
KadabraPicFront::     INCBIN "gfx/pokemon/front/kadabra.pic"
KadabraPicBack::      INCBIN "gfx/pokemon/back/kadabrab.pic"
AlakazamPicFront::    INCBIN "gfx/pokemon/front/alakazam.pic"
AlakazamPicBack::     INCBIN "gfx/pokemon/back/alakazamb.pic"
MachopPicFront::      INCBIN "gfx/pokemon/front/machop.pic"
MachopPicBack::       INCBIN "gfx/pokemon/back/machopb.pic"
MachokePicFront::     INCBIN "gfx/pokemon/front/machoke.pic"
MachokePicBack::      INCBIN "gfx/pokemon/back/machokeb.pic"
MachampPicFront::     INCBIN "gfx/pokemon/front/machamp.pic"
MachampPicBack::      INCBIN "gfx/pokemon/back/machampb.pic"
BellsproutPicFront::  INCBIN "gfx/pokemon/front/bellsprout.pic"
BellsproutPicBack::   INCBIN "gfx/pokemon/back/bellsproutb.pic"
WeepinbellPicFront::  INCBIN "gfx/pokemon/front/weepinbell.pic"
WeepinbellPicBack::   INCBIN "gfx/pokemon/back/weepinbellb.pic"
VictreebelPicFront::  INCBIN "gfx/pokemon/front/victreebel.pic"
VictreebelPicBack::   INCBIN "gfx/pokemon/back/victreebelb.pic"
TentacoolPicFront::   INCBIN "gfx/pokemon/front/tentacool.pic"
TentacoolPicBack::    INCBIN "gfx/pokemon/back/tentacoolb.pic"
TentacruelPicFront::  INCBIN "gfx/pokemon/front/tentacruel.pic"
TentacruelPicBack::   INCBIN "gfx/pokemon/back/tentacruelb.pic"
GeodudePicFront::     INCBIN "gfx/pokemon/front/geodude.pic"
GeodudePicBack::      INCBIN "gfx/pokemon/back/geodudeb.pic"

	ds $2c


SECTION "Pics 4", ROMX

GravelerPicFront::   INCBIN "gfx/pokemon/front/graveler.pic"
GravelerPicBack::    INCBIN "gfx/pokemon/back/gravelerb.pic"
GolemPicFront::      INCBIN "gfx/pokemon/front/golem.pic"
GolemPicBack::       INCBIN "gfx/pokemon/back/golemb.pic"
PonytaPicFront::     INCBIN "gfx/pokemon/front/ponyta.pic"
PonytaPicBack::      INCBIN "gfx/pokemon/back/ponytab.pic"
RapidashPicFront::   INCBIN "gfx/pokemon/front/rapidash.pic"
RapidashPicBack::    INCBIN "gfx/pokemon/back/rapidashb.pic"
SlowpokePicFront::   INCBIN "gfx/pokemon/front/slowpoke.pic"
SlowpokePicBack::    INCBIN "gfx/pokemon/back/slowpokeb.pic"
SlowbroPicFront::    INCBIN "gfx/pokemon/front/slowbro.pic"
SlowbroPicBack::     INCBIN "gfx/pokemon/back/slowbrob.pic"
MagnemitePicFront::  INCBIN "gfx/pokemon/front/magnemite.pic"
MagnemitePicBack::   INCBIN "gfx/pokemon/back/magnemiteb.pic"
MagnetonPicFront::   INCBIN "gfx/pokemon/front/magneton.pic"
MagnetonPicBack::    INCBIN "gfx/pokemon/back/magnetonb.pic"
FarfetchdPicFront::  INCBIN "gfx/pokemon/front/farfetchd.pic"
FarfetchdPicBack::   INCBIN "gfx/pokemon/back/farfetchdb.pic"
DoduoPicFront::      INCBIN "gfx/pokemon/front/doduo.pic"
DoduoPicBack::       INCBIN "gfx/pokemon/back/doduob.pic"
DodrioPicFront::     INCBIN "gfx/pokemon/front/dodrio.pic"
DodrioPicBack::      INCBIN "gfx/pokemon/back/dodriob.pic"
SeelPicFront::       INCBIN "gfx/pokemon/front/seel.pic"
SeelPicBack::        INCBIN "gfx/pokemon/back/seelb.pic"
DewgongPicFront::    INCBIN "gfx/pokemon/front/dewgong.pic"
DewgongPicBack::     INCBIN "gfx/pokemon/back/dewgongb.pic"
GrimerPicFront::     INCBIN "gfx/pokemon/front/grimer.pic"
GrimerPicBack::      INCBIN "gfx/pokemon/back/grimerb.pic"
MukPicFront::        INCBIN "gfx/pokemon/front/muk.pic"
MukPicBack::         INCBIN "gfx/pokemon/back/mukb.pic"
ShellderPicFront::   INCBIN "gfx/pokemon/front/shellder.pic"
ShellderPicBack::    INCBIN "gfx/pokemon/back/shellderb.pic"
CloysterPicFront::   INCBIN "gfx/pokemon/front/cloyster.pic"
CloysterPicBack::    INCBIN "gfx/pokemon/back/cloysterb.pic"
GastlyPicFront::     INCBIN "gfx/pokemon/front/gastly.pic"
GastlyPicBack::      INCBIN "gfx/pokemon/back/gastlyb.pic"
HaunterPicFront::    INCBIN "gfx/pokemon/front/haunter.pic"
HaunterPicBack::     INCBIN "gfx/pokemon/back/haunterb.pic"
GengarPicFront::     INCBIN "gfx/pokemon/front/gengar.pic"
GengarPicBack::      INCBIN "gfx/pokemon/back/gengarb.pic"
OnixPicFront::       INCBIN "gfx/pokemon/front/onix.pic"
OnixPicBack::        INCBIN "gfx/pokemon/back/onixb.pic"
DrowzeePicFront::    INCBIN "gfx/pokemon/front/drowzee.pic"
DrowzeePicBack::     INCBIN "gfx/pokemon/back/drowzeeb.pic"
HypnoPicFront::      INCBIN "gfx/pokemon/front/hypno.pic"
HypnoPicBack::       INCBIN "gfx/pokemon/back/hypnob.pic"
KrabbyPicFront::     INCBIN "gfx/pokemon/front/krabby.pic"
KrabbyPicBack::      INCBIN "gfx/pokemon/back/krabbyb.pic"

	ds $19d

RedPicBack::           INCBIN "gfx/player/redb.pic"
OldManPicBack::        INCBIN "gfx/battle/oldmanb.pic"


SECTION "Pics 5", ROMX

KinglerPicFront::      INCBIN "gfx/pokemon/front/kingler.pic"
KinglerPicBack::       INCBIN "gfx/pokemon/back/kinglerb.pic"
VoltorbPicFront::      INCBIN "gfx/pokemon/front/voltorb.pic"
VoltorbPicBack::       INCBIN "gfx/pokemon/back/voltorbb.pic"
ElectrodePicFront::    INCBIN "gfx/pokemon/front/electrode.pic"
ElectrodePicBack::     INCBIN "gfx/pokemon/back/electrodeb.pic"
ExeggcutePicFront::    INCBIN "gfx/pokemon/front/exeggcute.pic"
ExeggcutePicBack::     INCBIN "gfx/pokemon/back/exeggcuteb.pic"
ExeggutorPicFront::    INCBIN "gfx/pokemon/front/exeggutor.pic"
ExeggutorPicBack::     INCBIN "gfx/pokemon/back/exeggutorb.pic"
CubonePicFront::       INCBIN "gfx/pokemon/front/cubone.pic"
CubonePicBack::        INCBIN "gfx/pokemon/back/cuboneb.pic"
MarowakPicFront::      INCBIN "gfx/pokemon/front/marowak.pic"
MarowakPicBack::       INCBIN "gfx/pokemon/back/marowakb.pic"
HitmonleePicFront::    INCBIN "gfx/pokemon/front/hitmonlee.pic"
HitmonleePicBack::     INCBIN "gfx/pokemon/back/hitmonleeb.pic"
HitmonchanPicFront::   INCBIN "gfx/pokemon/front/hitmonchan.pic"
HitmonchanPicBack::    INCBIN "gfx/pokemon/back/hitmonchanb.pic"
LickitungPicFront::    INCBIN "gfx/pokemon/front/lickitung.pic"
LickitungPicBack::     INCBIN "gfx/pokemon/back/lickitungb.pic"
KoffingPicFront::      INCBIN "gfx/pokemon/front/koffing.pic"
KoffingPicBack::       INCBIN "gfx/pokemon/back/koffingb.pic"
WeezingPicFront::      INCBIN "gfx/pokemon/front/weezing.pic"
WeezingPicBack::       INCBIN "gfx/pokemon/back/weezingb.pic"
RhyhornPicFront::      INCBIN "gfx/pokemon/front/rhyhorn.pic"
RhyhornPicBack::       INCBIN "gfx/pokemon/back/rhyhornb.pic"
RhydonPicFront::       INCBIN "gfx/pokemon/front/rhydon.pic"
RhydonPicBack::        INCBIN "gfx/pokemon/back/rhydonb.pic"
ChanseyPicFront::      INCBIN "gfx/pokemon/front/chansey.pic"
ChanseyPicBack::       INCBIN "gfx/pokemon/back/chanseyb.pic"
TangelaPicFront::      INCBIN "gfx/pokemon/front/tangela.pic"
TangelaPicBack::       INCBIN "gfx/pokemon/back/tangelab.pic"
KangaskhanPicFront::   INCBIN "gfx/pokemon/front/kangaskhan.pic"
KangaskhanPicBack::    INCBIN "gfx/pokemon/back/kangaskhanb.pic"
HorseaPicFront::       INCBIN "gfx/pokemon/front/horsea.pic"
HorseaPicBack::        INCBIN "gfx/pokemon/back/horseab.pic"
FossilKabutopsPic::    INCBIN "gfx/pokemon/front/fossilkabutops.pic"
FossilAerodactylPic::  INCBIN "gfx/pokemon/front/fossilaerodactyl.pic"
GhostPic::             INCBIN "gfx/battle/ghost.pic"

	ds $42


SECTION "Pics 6", ROMX

TrainerPics::
YoungsterPic::     INCBIN "gfx/trainers/youngster.pic"
BugCatcherPic::    INCBIN "gfx/trainers/bugcatcher.pic"
LassPic::          INCBIN "gfx/trainers/lass.pic"
SailorPic::        INCBIN "gfx/trainers/sailor.pic"
JrTrainerMPic::    INCBIN "gfx/trainers/jr.trainerm.pic"
JrTrainerFPic::    INCBIN "gfx/trainers/jr.trainerf.pic"
PokemaniacPic::    INCBIN "gfx/trainers/pokemaniac.pic"
SuperNerdPic::     INCBIN "gfx/trainers/supernerd.pic"
HikerPic::         INCBIN "gfx/trainers/hiker.pic"
BikerPic::         INCBIN "gfx/trainers/biker.pic"
BurglarPic::       INCBIN "gfx/trainers/burglar.pic"
EngineerPic::      INCBIN "gfx/trainers/engineer.pic"
JugglerPic::       INCBIN "gfx/trainers/juggler.pic"
FisherPic::        INCBIN "gfx/trainers/fisher.pic"
SwimmerPic::       INCBIN "gfx/trainers/swimmer.pic"
CueBallPic::       INCBIN "gfx/trainers/cueball.pic"
GamblerPic::       INCBIN "gfx/trainers/gambler.pic"
BeautyPic::        INCBIN "gfx/trainers/beauty.pic"
PsychicPic::       INCBIN "gfx/trainers/psychic.pic"
RockerPic::        INCBIN "gfx/trainers/rocker.pic"
TamerPic::         INCBIN "gfx/trainers/tamer.pic"
BirdKeeperPic::    INCBIN "gfx/trainers/birdkeeper.pic"
BlackbeltPic::     INCBIN "gfx/trainers/blackbelt.pic"
Rival1Pic::        INCBIN "gfx/trainers/rival1.pic"
ProfOakPic::       INCBIN "gfx/trainers/prof.oak.pic"
ChiefPic::
ScientistPic::     INCBIN "gfx/trainers/scientist.pic"
GiovanniPic::      INCBIN "gfx/trainers/giovanni.pic"
RocketPic::        INCBIN "gfx/trainers/rocket.pic"
CooltrainerMPic::  INCBIN "gfx/trainers/cooltrainerm.pic"
CooltrainerFPic::  INCBIN "gfx/trainers/cooltrainerf.pic"
BrunoPic::         INCBIN "gfx/trainers/bruno.pic"
BrockPic::         INCBIN "gfx/trainers/brock.pic"
MistyPic::         INCBIN "gfx/trainers/misty.pic"
LtSurgePic::       INCBIN "gfx/trainers/lt.surge.pic"
ErikaPic::         INCBIN "gfx/trainers/erika.pic"
KogaPic::          INCBIN "gfx/trainers/koga.pic"
BlainePic::        INCBIN "gfx/trainers/blaine.pic"
SabrinaPic::       INCBIN "gfx/trainers/sabrina.pic"
GentlemanPic::     INCBIN "gfx/trainers/gentleman.pic"
Rival2Pic::        INCBIN "gfx/trainers/rival2.pic"
Rival3Pic::        INCBIN "gfx/trainers/rival3.pic"
LoreleiPic::       INCBIN "gfx/trainers/lorelei.pic"
ChannelerPic::     INCBIN "gfx/trainers/channeler.pic"
AgathaPic::        INCBIN "gfx/trainers/agatha.pic"
LancePic::         INCBIN "gfx/trainers/lance.pic"

	ds $355
